function GillBalentine::loadass(%this)
{

%this.image_td_down_attack1=AssetDatabase.acquireAsset("GillBalentine:image_td_down_attack1");
%this.image_td_down_attack2=AssetDatabase.acquireAsset("GillBalentine:image_td_down_attack2");
%this.image_td_down_jump=AssetDatabase.acquireAsset("GillBalentine:image_td_down_jump");
%this.image_td_down_run=AssetDatabase.acquireAsset("GillBalentine:image_td_down_run");
%this.image_td_down_stand=AssetDatabase.acquireAsset("GillBalentine:image_td_down_stand");
%this.image_td_down_swim=AssetDatabase.acquireAsset("GillBalentine:image_td_down_swim");
%this.image_td_left_attack1=AssetDatabase.acquireAsset("GillBalentine:image_td_left_attack1");
%this.image_td_left_attack2=AssetDatabase.acquireAsset("GillBalentine:image_td_left_attack2");
%this.image_td_left_jump=AssetDatabase.acquireAsset("GillBalentine:image_td_left_jump");
%this.image_td_left_run=AssetDatabase.acquireAsset("GillBalentine:image_td_left_run");
%this.image_td_left_stand=AssetDatabase.acquireAsset("GillBalentine:image_td_left_stand");
%this.image_td_left_swim=AssetDatabase.acquireAsset("GillBalentine:image_td_left_swim");
%this.image_td_right_attack1=AssetDatabase.acquireAsset("GillBalentine:image_td_right_attack1");
%this.image_td_right_attack2=AssetDatabase.acquireAsset("GillBalentine:image_td_right_attack2");
%this.image_td_right_jump=AssetDatabase.acquireAsset("GillBalentine:image_td_right_jump");
%this.image_td_right_run=AssetDatabase.acquireAsset("GillBalentine:image_td_right_run");
%this.image_td_right_stand=AssetDatabase.acquireAsset("GillBalentine:image_td_right_stand");
%this.image_td_right_swim=AssetDatabase.acquireAsset("GillBalentine:image_td_right_swim");
%this.image_td_up_attack1=AssetDatabase.acquireAsset("GillBalentine:image_td_up_attack1");
%this.image_td_up_attack2=AssetDatabase.acquireAsset("GillBalentine:image_td_up_attack2");
%this.image_td_up_jump=AssetDatabase.acquireAsset("GillBalentine:image_td_up_jump");
%this.image_td_up_run=AssetDatabase.acquireAsset("GillBalentine:image_td_up_run");
%this.image_td_up_stand=AssetDatabase.acquireAsset("GillBalentine:image_td_up_stand");
%this.image_td_up_swim=AssetDatabase.acquireAsset("GillBalentine:image_td_up_swim");

%this.image_sv_down_attack1=AssetDatabase.acquireAsset("GillBalentine:image_sv_down_attack1");
%this.image_sv_down_attack2=AssetDatabase.acquireAsset("GillBalentine:image_sv_down_attack2");
%this.image_sv_down_jump=AssetDatabase.acquireAsset("GillBalentine:image_sv_down_jump");
%this.image_sv_down_run=AssetDatabase.acquireAsset("GillBalentine:image_sv_down_run");
%this.image_sv_down_stand=AssetDatabase.acquireAsset("GillBalentine:image_sv_down_stand");
%this.image_sv_down_swim=AssetDatabase.acquireAsset("GillBalentine:image_sv_down_swim");
%this.image_sv_left_attack1=AssetDatabase.acquireAsset("GillBalentine:image_sv_left_attack1");
%this.image_sv_left_attack2=AssetDatabase.acquireAsset("GillBalentine:image_sv_left_attack2");
%this.image_sv_left_jump=AssetDatabase.acquireAsset("GillBalentine:image_sv_left_jump");
%this.image_sv_left_run=AssetDatabase.acquireAsset("GillBalentine:image_sv_left_run");
%this.image_sv_left_stand=AssetDatabase.acquireAsset("GillBalentine:image_sv_left_stand");
%this.image_sv_left_swim=AssetDatabase.acquireAsset("GillBalentine:image_sv_left_swim");
%this.image_sv_right_attack1=AssetDatabase.acquireAsset("GillBalentine:image_sv_right_attack1");
%this.image_sv_right_attack2=AssetDatabase.acquireAsset("GillBalentine:image_sv_right_attack2");
%this.image_sv_right_jump=AssetDatabase.acquireAsset("GillBalentine:image_sv_right_jump");
%this.image_sv_right_run=AssetDatabase.acquireAsset("GillBalentine:image_sv_right_run");
%this.image_sv_right_stand=AssetDatabase.acquireAsset("GillBalentine:image_sv_right_stand");
%this.image_sv_right_swim=AssetDatabase.acquireAsset("GillBalentine:image_sv_right_swim");
%this.image_sv_up_attack1=AssetDatabase.acquireAsset("GillBalentine:image_sv_up_attack1");
%this.image_sv_up_attack2=AssetDatabase.acquireAsset("GillBalentine:image_sv_up_attack2");
%this.image_sv_up_jump=AssetDatabase.acquireAsset("GillBalentine:image_sv_up_jump");
%this.image_sv_up_run=AssetDatabase.acquireAsset("GillBalentine:image_sv_up_run");
%this.image_sv_up_stand=AssetDatabase.acquireAsset("GillBalentine:image_sv_up_stand");
%this.image_sv_up_swim=AssetDatabase.acquireAsset("GillBalentine:image_sv_up_swim");

}
