function GillBalentine::unloadass(%this)
{

AssetDatabase.releaseAsset(%this.image_td_down_attack1.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_down_attack2.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_down_jump.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_down_run.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_down_stand.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_down_swim.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_left_attack1.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_left_attack2.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_left_jump.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_left_run.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_left_stand.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_left_swim.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_right_attack1.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_right_attack2.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_right_jump.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_right_run.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_right_stand.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_right_swim.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_up_attack1.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_up_attack2.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_up_jump.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_up_run.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_up_stand.getAssetId());
AssetDatabase.releaseAsset(%this.image_td_up_swim.getAssetId());

AssetDatabase.releaseAsset(%this.image_sv_down_attack1.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_down_attack2.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_down_jump.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_down_run.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_down_stand.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_down_swim.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_left_attack1.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_left_attack2.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_left_jump.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_left_run.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_left_stand.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_left_swim.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_right_attack1.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_right_attack2.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_right_jump.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_right_run.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_right_stand.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_right_swim.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_up_attack1.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_up_attack2.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_up_jump.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_up_run.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_up_stand.getAssetId());
AssetDatabase.releaseAsset(%this.image_sv_up_swim.getAssetId());

}
